name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          
      - run: TAG=$(git ls-remote remote "refs/tags/v*[0-9]" | cut -f 2- | sort -V | tail -1)

      - name: Get latest tag
        run: |
          git fetch -a
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $latest_tag
