name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get latest tag
        run: |
          git fetch -a
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $latest_tag
